package gg.fel.cvut.cz.enums;

import bwapi.WeaponType;
import java.util.List;

public enum WeaponTypeEnum implements IGameTypes<WeaponType, WeaponTypeEnum> {
  GaussRifle,
  GaussRifleJimRaynor,
  C10CanisterRifle,
  C10CanisterRifleSarahKerrigan,
  C10CanisterRifleSamirDuran,
  C10CanisterRifleInfestedDuran,
  C10CanisterRifleAlexeiStukov,
  FragmentationGrenade,
  FragmentationGrenadeJimRaynor,
  SpiderMines,
  TwinAutocannons,
  TwinAutocannonsAlanSchezar,
  HellfireMissilePack,
  HellfireMissilePackAlanSchezar,
  ArcliteCannon,
  ArcliteCannonEdmundDuke,
  FusionCutter,
  GeminiMissiles,
  GeminiMissilesTomKazansky,
  BurstLasers,
  BurstLasersTomKazansky,
  ATSLaserBattery,
  ATSLaserBatteryHero,
  ATSLaserBatteryHyperion,
  ATALaserBattery,
  ATALaserBatteryHero,
  ATALaserBatteryHyperion,
  FlameThrower,
  FlameThrowerGuiMontag,
  ArcliteShockCannon,
  ArcliteShockCannonEdmundDuke,
  LongboltMissile,
  Claws,
  ClawsDevouringOne,
  ClawsInfestedKerrigan,
  NeedleSpines,
  NeedleSpinesHunterKiller,
  KaiserBlades,
  KaiserBladesTorrasque,
  ToxicSpores,
  Spines,
  AcidSpore,
  AcidSporeKukulza,
  GlaveWurm,
  GlaveWurmKukulza,
  SeekerSpores,
  SubterraneanTentacle,
  SuicideInfestedTerran,
  SuicideScourge,
  ParticleBeam,
  PsiBlades,
  PsiBladesFenix,
  PhaseDisruptor,
  PhaseDisruptorFenix,
  PsiAssault,
  PsionicShockwave,
  PsionicShockwaveTZArchon,
  DualPhotonBlasters,
  DualPhotonBlastersMojo,
  DualPhotonBlastersArtanis,
  AntiMatterMissiles,
  AntiMatterMissilesMojo,
  AntiMatterMissilesArtanis,
  PhaseDisruptorCannon,
  PhaseDisruptorCannonDanimoth,
  PulseCannon,
  STSPhotonCannon,
  STAPhotonCannon,
  Scarab,
  NeutronFlare,
  HaloRockets,
  CorrosiveAcid,
  SubterraneanSpines,
  WarpBlades,
  WarpBladesHero,
  WarpBladesZeratul,
  IndependantLaserBattery,
  TwinAutocannonsFloorTrap,
  HellfireMissilePackWallTrap,
  FlameThrowerWallTrap,
  HellfireMissilePackFloorTrap,
  YamatoGun,
  NuclearStrike,
  Lockdown,
  EMPShockwave,
  Irradiate,
  Parasite,
  SpawnBroodlings,
  Ensnare,
  DarkSwarm,
  Plague,
  Consume,
  StasisField,
  PsionicStorm,
  DisruptionWeb,
  Restoration,
  MindControl,
  Feedback,
  OpticalFlare,
  Maelstrom,
  None,
  Unknown;

  @Override
  public List<WeaponType> getTypes() {
    return WEAPON_TYPES;
  }

  @Override
  public WeaponTypeEnum[] getValues() {
    return WeaponTypeEnum.values();
  }
}
